# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1827b7b2a666189c16a117086a7f0e2a3bf2cc16269182650565daa56bbd68098740763ef4ec4f61112667ddc725e92c6f09874847709d3851a4109ad4036056

test:
  secret_key_base: 77549f636ce803989e3073430f8acccec41e79ed51975197124624e4cb8e362a0463983bc62da1b57c6b144ea1309648f565b1b4ffbb078d5b140b1ee0ab2b75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 2488ec142d4c01b67735fae495bd24f76db51a0229672cc7ed113b69b4101b58a3c7b4b195d77eaf24b08cfe87f234a80f24a6df2de1dfbf8dae51903c6c0104
